// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/media_scan/data/entities/media_item_entity.dart';
import 'shared/entities/processing_job_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 1871724471495849408),
    name: 'MediaItemEntity',
    lastPropertyId: const obx_int.IdUid(17, 6872030586065759701),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7912872319080499120),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8899341211315357374),
        name: 'path',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 231070403437001552),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1731484136215277215),
        name: 'fileName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7750241892291661588),
        name: 'mimeType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6045148217430310894),
        name: 'sizeBytes',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3450765257922563449),
        name: 'width',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1985454646145909482),
        name: 'height',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3321316346711059932),
        name: 'createdAtEpochMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6300618404634522024),
        name: 'modifiedAtEpochMs',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7295664149770634358),
        name: 'contentVersionKey',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 5102864900650167305),
        name: 'analysisStatus',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4203226696221580702),
        name: 'sha256',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8286564969043688500),
        name: 'perceptualHashHex',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 8061201723810220622),
        name: 'embeddingJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7456806830928911432),
        name: 'thumbnailPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 3297350643913640041),
        name: 'sourceRoot',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 6872030586065759701),
        name: 'lastScannedAtEpochMs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7354469289138532160),
    name: 'ProcessingJobEntity',
    lastPropertyId: const obx_int.IdUid(8, 7437714620532884246),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5061937952334110185),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2641523194133510347),
        name: 'jobKey',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 8364997570123008728),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6373865595034901252),
        name: 'stage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8154803046008952700),
        name: 'message',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4419301105279060844),
        name: 'progress',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6641461534971078221),
        name: 'selectedSource',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 8395099639560539397),
        name: 'failureReason',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7437714620532884246),
        name: 'updatedAtEpochMs',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 7354469289138532160),
    lastIndexId: const obx_int.IdUid(2, 8364997570123008728),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    MediaItemEntity: obx_int.EntityDefinition<MediaItemEntity>(
      model: _entities[0],
      toOneRelations: (MediaItemEntity object) => [],
      toManyRelations: (MediaItemEntity object) => {},
      getId: (MediaItemEntity object) => object.id,
      setId: (MediaItemEntity object, int id) {
        object.id = id;
      },
      objectToFB: (MediaItemEntity object, fb.Builder fbb) {
        final pathOffset = fbb.writeString(object.path);
        final fileNameOffset = fbb.writeString(object.fileName);
        final mimeTypeOffset = fbb.writeString(object.mimeType);
        final contentVersionKeyOffset = fbb.writeString(
          object.contentVersionKey,
        );
        final analysisStatusOffset = fbb.writeString(object.analysisStatus);
        final sha256Offset = fbb.writeString(object.sha256);
        final perceptualHashHexOffset = fbb.writeString(
          object.perceptualHashHex,
        );
        final embeddingJsonOffset = fbb.writeString(object.embeddingJson);
        final thumbnailPathOffset = object.thumbnailPath == null
            ? null
            : fbb.writeString(object.thumbnailPath!);
        final sourceRootOffset = object.sourceRoot == null
            ? null
            : fbb.writeString(object.sourceRoot!);
        fbb.startTable(18);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, pathOffset);
        fbb.addOffset(2, fileNameOffset);
        fbb.addOffset(3, mimeTypeOffset);
        fbb.addInt64(4, object.sizeBytes);
        fbb.addInt64(5, object.width);
        fbb.addInt64(6, object.height);
        fbb.addInt64(7, object.createdAtEpochMs);
        fbb.addInt64(8, object.modifiedAtEpochMs);
        fbb.addOffset(9, contentVersionKeyOffset);
        fbb.addOffset(10, analysisStatusOffset);
        fbb.addOffset(11, sha256Offset);
        fbb.addOffset(12, perceptualHashHexOffset);
        fbb.addOffset(13, embeddingJsonOffset);
        fbb.addOffset(14, thumbnailPathOffset);
        fbb.addOffset(15, sourceRootOffset);
        fbb.addInt64(16, object.lastScannedAtEpochMs);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final pathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final fileNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final mimeTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final sizeBytesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final widthParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final heightParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final createdAtEpochMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final modifiedAtEpochMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final contentVersionKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final analysisStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final sha256Param = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 26, '');
        final perceptualHashHexParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 28, '');
        final embeddingJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final thumbnailPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final sourceRootParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final lastScannedAtEpochMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          36,
          0,
        );
        final object = MediaItemEntity(
          id: idParam,
          path: pathParam,
          fileName: fileNameParam,
          mimeType: mimeTypeParam,
          sizeBytes: sizeBytesParam,
          width: widthParam,
          height: heightParam,
          createdAtEpochMs: createdAtEpochMsParam,
          modifiedAtEpochMs: modifiedAtEpochMsParam,
          contentVersionKey: contentVersionKeyParam,
          analysisStatus: analysisStatusParam,
          sha256: sha256Param,
          perceptualHashHex: perceptualHashHexParam,
          embeddingJson: embeddingJsonParam,
          thumbnailPath: thumbnailPathParam,
          sourceRoot: sourceRootParam,
          lastScannedAtEpochMs: lastScannedAtEpochMsParam,
        );

        return object;
      },
    ),
    ProcessingJobEntity: obx_int.EntityDefinition<ProcessingJobEntity>(
      model: _entities[1],
      toOneRelations: (ProcessingJobEntity object) => [],
      toManyRelations: (ProcessingJobEntity object) => {},
      getId: (ProcessingJobEntity object) => object.id,
      setId: (ProcessingJobEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ProcessingJobEntity object, fb.Builder fbb) {
        final jobKeyOffset = fbb.writeString(object.jobKey);
        final stageOffset = fbb.writeString(object.stage);
        final messageOffset = fbb.writeString(object.message);
        final selectedSourceOffset = object.selectedSource == null
            ? null
            : fbb.writeString(object.selectedSource!);
        final failureReasonOffset = object.failureReason == null
            ? null
            : fbb.writeString(object.failureReason!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, jobKeyOffset);
        fbb.addOffset(2, stageOffset);
        fbb.addOffset(3, messageOffset);
        fbb.addFloat64(4, object.progress);
        fbb.addOffset(5, selectedSourceOffset);
        fbb.addOffset(6, failureReasonOffset);
        fbb.addInt64(7, object.updatedAtEpochMs);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final jobKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final stageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final messageParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final progressParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final selectedSourceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 14);
        final failureReasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final updatedAtEpochMsParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final object = ProcessingJobEntity(
          id: idParam,
          jobKey: jobKeyParam,
          stage: stageParam,
          message: messageParam,
          progress: progressParam,
          selectedSource: selectedSourceParam,
          failureReason: failureReasonParam,
          updatedAtEpochMs: updatedAtEpochMsParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [MediaItemEntity] entity fields to define ObjectBox queries.
class MediaItemEntity_ {
  /// See [MediaItemEntity.id].
  static final id = obx.QueryIntegerProperty<MediaItemEntity>(
    _entities[0].properties[0],
  );

  /// See [MediaItemEntity.path].
  static final path = obx.QueryStringProperty<MediaItemEntity>(
    _entities[0].properties[1],
  );

  /// See [MediaItemEntity.fileName].
  static final fileName = obx.QueryStringProperty<MediaItemEntity>(
    _entities[0].properties[2],
  );

  /// See [MediaItemEntity.mimeType].
  static final mimeType = obx.QueryStringProperty<MediaItemEntity>(
    _entities[0].properties[3],
  );

  /// See [MediaItemEntity.sizeBytes].
  static final sizeBytes = obx.QueryIntegerProperty<MediaItemEntity>(
    _entities[0].properties[4],
  );

  /// See [MediaItemEntity.width].
  static final width = obx.QueryIntegerProperty<MediaItemEntity>(
    _entities[0].properties[5],
  );

  /// See [MediaItemEntity.height].
  static final height = obx.QueryIntegerProperty<MediaItemEntity>(
    _entities[0].properties[6],
  );

  /// See [MediaItemEntity.createdAtEpochMs].
  static final createdAtEpochMs = obx.QueryIntegerProperty<MediaItemEntity>(
    _entities[0].properties[7],
  );

  /// See [MediaItemEntity.modifiedAtEpochMs].
  static final modifiedAtEpochMs = obx.QueryIntegerProperty<MediaItemEntity>(
    _entities[0].properties[8],
  );

  /// See [MediaItemEntity.contentVersionKey].
  static final contentVersionKey = obx.QueryStringProperty<MediaItemEntity>(
    _entities[0].properties[9],
  );

  /// See [MediaItemEntity.analysisStatus].
  static final analysisStatus = obx.QueryStringProperty<MediaItemEntity>(
    _entities[0].properties[10],
  );

  /// See [MediaItemEntity.sha256].
  static final sha256 = obx.QueryStringProperty<MediaItemEntity>(
    _entities[0].properties[11],
  );

  /// See [MediaItemEntity.perceptualHashHex].
  static final perceptualHashHex = obx.QueryStringProperty<MediaItemEntity>(
    _entities[0].properties[12],
  );

  /// See [MediaItemEntity.embeddingJson].
  static final embeddingJson = obx.QueryStringProperty<MediaItemEntity>(
    _entities[0].properties[13],
  );

  /// See [MediaItemEntity.thumbnailPath].
  static final thumbnailPath = obx.QueryStringProperty<MediaItemEntity>(
    _entities[0].properties[14],
  );

  /// See [MediaItemEntity.sourceRoot].
  static final sourceRoot = obx.QueryStringProperty<MediaItemEntity>(
    _entities[0].properties[15],
  );

  /// See [MediaItemEntity.lastScannedAtEpochMs].
  static final lastScannedAtEpochMs = obx.QueryIntegerProperty<MediaItemEntity>(
    _entities[0].properties[16],
  );
}

/// [ProcessingJobEntity] entity fields to define ObjectBox queries.
class ProcessingJobEntity_ {
  /// See [ProcessingJobEntity.id].
  static final id = obx.QueryIntegerProperty<ProcessingJobEntity>(
    _entities[1].properties[0],
  );

  /// See [ProcessingJobEntity.jobKey].
  static final jobKey = obx.QueryStringProperty<ProcessingJobEntity>(
    _entities[1].properties[1],
  );

  /// See [ProcessingJobEntity.stage].
  static final stage = obx.QueryStringProperty<ProcessingJobEntity>(
    _entities[1].properties[2],
  );

  /// See [ProcessingJobEntity.message].
  static final message = obx.QueryStringProperty<ProcessingJobEntity>(
    _entities[1].properties[3],
  );

  /// See [ProcessingJobEntity.progress].
  static final progress = obx.QueryDoubleProperty<ProcessingJobEntity>(
    _entities[1].properties[4],
  );

  /// See [ProcessingJobEntity.selectedSource].
  static final selectedSource = obx.QueryStringProperty<ProcessingJobEntity>(
    _entities[1].properties[5],
  );

  /// See [ProcessingJobEntity.failureReason].
  static final failureReason = obx.QueryStringProperty<ProcessingJobEntity>(
    _entities[1].properties[6],
  );

  /// See [ProcessingJobEntity.updatedAtEpochMs].
  static final updatedAtEpochMs = obx.QueryIntegerProperty<ProcessingJobEntity>(
    _entities[1].properties[7],
  );
}
